tests: fix subproject build
Fix compile warning due to missing phosphor-logging header when
compiled with meson subprojects by adding the appropriate dependency.

```
In file included from ../test/test_instance_id.hpp:3,
                 from ../test/instance_id_test.cpp:1:
../common/instance_id.hpp:5:10: fatal error: phosphor-logging/lg2.hpp: No such file or directory
    5 | #include <phosphor-logging/lg2.hpp>
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I36a178940e794bb2d12ccbbb4170b2a143c4e528