oem-ibm: libpldmresponder: oem_ibm_handler: Remove unused `this`
```
../oem/ibm/libpldmresponder/oem_ibm_handler.hpp:101:14: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  101 |             [this](sdbusplus::message_t& msg) {
      |              ^~~~
```

Change-Id: I155758a25488d747eed2af0ac24407561ab3cc9f
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>