oem-ibm: requester: dbus_to_file_handler: Drop unused mctp_fd
```
../oem/ibm/requester/dbus_to_file_handler.hpp:83:9: error: private field 'mctp_fd' is not used [-Werror,-Wunused-private-field]
   83 |     int mctp_fd;
      |         ^
```

Change-Id: I03751463e91b5f62c1e60c1ef47c22dcfcc20215
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>