clang-diagnostic error: no member in the namespace 'std'
Clang was throwing no member named in 'std' error due to missing
inclusions.

Change-Id: I50d12ff604f2e9050b1d19891d3dbb80b878736f
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>