fix type deduction failure in gcc-14
Looks like gcc-14 has even more strict & more accurate compile time
checks and the current pldm code does not compile with gcc-14 and
reports the following error:

```
03:20:47 | ../git/platform-mc/terminus_manager.cpp: In member function 'exec::task<int> pldm::platform_mc::TerminusManager::discoverMctpTerminusTask()':
03:20:47 | ../git/platform-mc/terminus_manager.cpp:173:38: error: use of 'auto pldm::platform_mc::TerminusManager::findTerminusPtr(const pldm::MctpInfo&)' before deduction of 'auto'
03:20:47 |   173 |             auto it = findTerminusPtr(mctpInfo);
03:20:47 |       |                       ~~~~~~~~~~~~~~~^~~~~~~~~~
03:20:47 | ../git/platform-mc/terminus_manager.cpp: In member function 'void pldm::platform_mc::TerminusManager::removeMctpTerminus(const pldm::MctpInfos&)':
03:20:47 | ../git/platform-mc/terminus_manager.cpp:196:34: error: use of 'auto pldm::platform_mc::TerminusManager::findTerminusPtr(const pldm::MctpInfo&)' before deduction of 'auto'
03:20:47 |   196 |         auto it = findTerminusPtr(mctpInfo);

```

compiler seems to be confused to decude the type for `auto`. Since
we already have a type definition, directly using that to feed
some extra information to the compiler at build time.

Change-Id: I4363afb5fc5f6177c96d313ac88be22418805fbd
Signed-off-by: Manojkiran Eda <manojkiran.eda@gmail.com>