fully qualify pdr namespace
event_sensor.hpp sometimes fails to build with:

```
error: ‘ContainerID’ in namespace ‘pldm::responder::pdr’ does not name a type
```

depending on the location in which event_sensor.hpp is included relative
to other pldm header files.

Fully qualify the namespace so that ordering is not required.

Change-Id: I6658da7052e14763d0c10fc8c0c5c91e3fb1ac6c
Signed-off-by: Brad Bishop <bradbish@qti.qualcomm.com>