host-bmc: host_pdr_handler: Drop unused emptyJsonList
```
../host-bmc/host_pdr_handler.cpp:35:25: error: unused variable 'emptyJsonList' [-Werror,-Wunused-const-variable]
   35 | const std::vector<Json> emptyJsonList{};
      |                         ^~~~~~~~~~~~~
```

Change-Id: I25d48daea746ab61caa5c582225ef5ae7ae1c4a3
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>