oem-ibm: libpldmresponder: file_io: Remove unused fields
```
../oem/ibm/libpldmresponder/file_io.hpp:418:9: error: private field 'hostSockFd' is not used [-Werror,-Wunused-private-field]
  418 |     int hostSockFd;
      |         ^
../oem/ibm/libpldmresponder/file_io.hpp:419:13: error: private field 'hostEid' is not used [-Werror,-Wunused-private-field]
  419 |     uint8_t hostEid;
      |             ^
../oem/ibm/libpldmresponder/file_io.hpp:420:25: error: private field 'instanceIdDb' is not used [-Werror,-Wunused-private-field]
  420 |     pldm::InstanceIdDb* instanceIdDb;
      |                         ^
../oem/ibm/libpldmresponder/file_io.hpp:433:57: error: private field 'handler' is not used [-Werror,-Wunused-private-field]
  433 |     pldm::requester::Handler<pldm::requester::Request>* handler;
      |
```

Change-Id: Ifd2e813423b7bc0bd67780c0fc21e32cf8de3e85
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>