clang-diagnostic error: error: use of undeclared identifiers
Clang was throwing use of undeclared identifiers for 'std',
'uint8_t', 'uint16_t' and expected unqualified-id errors
due to missing inclusions.

Change-Id: I072eb27ee7a89e215afdd10f095b82c12be62599
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>