clang-diagnostic error: undeclared identifier
Clang was throwing errors like 'use of undeclared identifier',
'unknown type name' due to missing namespace decalarations.

Change-Id: If26471aed22be470680175c31a916a4184e30bd2
Signed-off-by: Pavithra Barithaya <pavithrabarithaya07@gmail.com>