handleRequest use start_lifetime_as consistenly
GCC16 returned an error w.r.t. potentially uninitialized data in
`relayedResponseMsg->payload[0]` and replacing that with
start_lifetime_as does not result in compilation error.

```
../fw-update/aggregate_update_manager.cpp: In member function ‘virtual pldm::Response pldm::fw_update::AggregateUpdateManager::handleRequest(mctp_eid_t, uint8_t, const pldm_msg*, size_t)’:
../fw-update/aggregate_update_manager.cpp:25:42: error: ‘*(pldm_msg*)MEM[(struct vector *)response_8(D)].D.366301._M_impl.D.365600._M_start.pldm_msg::payload[0]’ may be used uninitialized [-Werror=maybe-uninitialized]
   25 |         if (relayedResponseMsg->payload[0] != PLDM_FWUP_COMMAND_NOT_EXPECTED)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Also improves consistency with how the response is handled.

Tested: Inspection only, relying on review since i don't have pldm
devices.

Change-Id: Ic6df829957a239844b42ae97ded2d6400372ccf0
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>