Revert "platform-mc: Add 64-bit numeric sensor support"
This reverts commit e1e59bc6ebf461d7f125a526004ac9c98b7af4bb.

The corresponding libpldm commit[1] has not yet been merged. pldm now
fails to build with e.g:

```
../platform-mc/sensor_manager.cpp: In member function ‘exec::task<int> pldm::platform_mc::SensorManager::getSensorReading(std::shared_ptr<pldm::platform_mc::NumericSensor>)’:
../platform-mc/sensor_manager.cpp:336:30: error: ‘PLDM_SENSOR_DATA_SIZE_SINT64’ was not declared in this scope; did you mean ‘PLDM_SENSOR_DATA_SIZE_SINT8’?
  336 |     uint8_t sensorDataSize = PLDM_SENSOR_DATA_SIZE_SINT64;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              PLDM_SENSOR_DATA_SIZE_SINT8
```

[1]: https://gerrit.openbmc.org/c/openbmc/libpldm/+/84665

Change-Id: I1f9d33dd813bc65b4f5bc932cebd7b51cd41ca00
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>