host-bmc: dbus_to_event_handler: Remove unused mctp_fd
```
../host-bmc/dbus_to_event_handler.hpp:89:9: error: private field 'mctp_fd' is not used [-Werror,-Wunused-private-field]
   89 |     int mctp_fd;
      |         ^
```

Change-Id: Ia17471784594bf0abfc7ec5fca4c37aff274ecd0
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>