meson: pldmtool: fix subproject build
pldmtool uses headers from phosphor-logging for lg2 support, but
was missing the phosphor-logging dependency.  Add the dependency
back in, which fixes subproject-based builds.

Without this change the following failure is observed:
```
In file included from ../pldmtool/pldm_cmd_helper.hpp:4,
                 from ../pldmtool/pldm_cmd_helper.cpp:1:
../common/utils.hpp:15:10: fatal error: phosphor-logging/lg2.hpp: No such file or directory
   15 | #include <phosphor-logging/lg2.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

With the change, the build is successful.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Id4ca9e7a01e3dfb8b93cbb8da4094264923c3e4d