wstring_convert: pragma out deprecation warning
With GCC 15, we are starting to see the following warnings:

```
15:17:59 | ../git/platform-mc/terminus.cpp:333:22: error: 'template<class _Codecvt, class _Elem, class _Wide_alloc, class _Byte_alloc> class std::__cxx11::wstring_convert' is deprecated [-Werror=deprecated-declarations]
```

Insert pragmas around them until another solution is found, so that
we can perform the next Yocto upgrade.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I4132eec42b79cd7f3c18b9b1798e8f871241328b